# ============================================================
# Spring Application & Eureka Registration Setup
# ============================================================
spring.application.name=Carofly-kafka-consumer-service


# Kafka Broker URL(s)
spring.kafka.bootstrap-servers=localhost:9092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Consumer Group & Offset Behavior
spring.kafka.consumer.group-id=carofly-consumer-eureka-id
spring.kafka.consumer.auto-offset-reset=earliest

# String Key/Value Deserializers (Change to JsonDeserializer if consuming JSON DTOs)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Optional: Concurrency tuning (number of listener threads)
spring.kafka.listener.concurrency=3